import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'dark_theme_enabled': 'Dark theme enabled',
      'light_theme_enabled': 'Light theme enabled',
      'language': 'Language',
      'english': 'English',
      'hindi': 'Hindi',
      'data_history': 'Data & History',
      'monthly_history': 'Monthly History',
      'all_transactions': 'All Transactions',
      'backup_restore': 'Backup & Restore',
      'backup_info': 'Backups include all inventory data, party records, orders, and transaction history.',
      'create_backup': 'Create Backup',
      'export_backup': 'Export database to a file and share',
      'restore_data': 'Restore Data',
      'import_backup': 'Import database from a backup file',
      'about': 'About',
      'app_name': 'Army Mess Inventory',
      'version': 'Version 2.0.0',
      'welcome': 'Welcome, Quartermaster',
      'quick_actions': 'Quick Actions',
      'stock_management': 'Stock Management',
      'manage_inventory': 'Manage inventory items',
      'daily_deduction': 'Daily Deduction',
      'record_usage': 'Record daily usage',
      'officer_party': 'Officer Party',
      'manage_party_bills': 'Manage party bills',
      'party_orders': 'Party Orders',
      'pre_party_ordering': 'Pre-party ordering',
      'ocr_bill_scan': 'OCR Bill Scan',
      'import_bills_auto': 'Import bills auto',
      'reports': 'Reports',
      'view_analytics': 'View analytics',
      'home': 'Home',
      'history': 'History',
    },
    'hi': {
      'settings': 'सेटिंग्स',
      'appearance': 'दिखावट',
      'dark_mode': 'डार्क मोड',
      'dark_theme_enabled': 'डार्क थीम सक्षम',
      'light_theme_enabled': 'लाइट थीम सक्षम',
      'language': 'भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिन्दी',
      'data_history': 'डेटा और इतिहास',
      'monthly_history': 'मासिक इतिहास',
      'all_transactions': 'सभी लेनदेन',
      'backup_restore': 'बैकअप और पुनर्स्थापना',
      'backup_info': 'बैकअप में सभी इन्वेंट्री डेटा, पार्टी रिकॉर्ड, ऑर्डर और लेनदेन इतिहास शामिल हैं।',
      'create_backup': 'बैकअप बनाएं',
      'export_backup': 'डेटाबेस को फ़ाइल में निर्यात करें और साझा करें',
      'restore_data': 'डेटा पुनर्स्थापित करें',
      'import_backup': 'बैकअप फ़ाइल से डेटाबेस आयात करें',
      'about': 'के बारे में',
      'app_name': 'आर्मी मेस इन्वेंट्री',
      'version': 'संस्करण 2.0.0',
      'welcome': 'स्वागत है, क्वार्टरमास्टर',
      'quick_actions': 'त्वरित कार्रवाई',
      'stock_management': 'स्टॉक प्रबंधन',
      'manage_inventory': 'इन्वेंट्री आइटम प्रबंधित करें',
      'daily_deduction': 'दैनिक कटौती',
      'record_usage': 'दैनिक उपयोग रिकॉर्ड करें',
      'officer_party': 'ऑफिसर पार्टी',
      'manage_party_bills': 'पार्टी बिल प्रबंधित करें',
      'party_orders': 'पार्टी ऑर्डर',
      'pre_party_ordering': 'पार्टी से पहले का ऑर्डर',
      'ocr_bill_scan': 'ओसीआर बिल स्कैन',
      'import_bills_auto': 'बिल ऑटो आयात करें',
      'reports': 'रिपोर्ट',
      'view_analytics': 'विश्लेषण देखें',
      'home': 'होम',
      'history': 'इतिहास',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
